services:
    api: 
        image: ghcr.io/bulkinod/shked-api:latest
        container_name: api
        env_file: ".env"
        restart: unless-stopped
        depends_on:
            - db
        
    auth:
        image: ghcr.io/bulkinod/shked-auth:latest
        container_name: auth
        env_file: ".env"
        restart: unless-stopped
        depends_on:
            - db

    db:
        image: postgres:17
        container_name: db
        env_file: ".env"
        restart: unless-stopped
        volumes:
            - pgdata:/var/lib/postgresql/data
    
    openresty:
        image: openresty/openresty:1.27.1.2-0-alpine-fat
        container_name: openresty
        env_file: ".env"
        restart: unless-stopped
        volumes: 
            - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
            - ./nginx/jwt.lua:/etc/nginx/lua/jwt.lua:ro
        


volumes:
    pgdata:

        