name: Build and Push Docker images

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ShkedAuth image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-auth:latest
          docker build -t $IMAGE_NAME ./ShkedAuth
          docker push $IMAGE_NAME

      - name: Build and push ShkedApi image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-api:latest
          docker build -t $IMAGE_NAME ./Shked
          docker push $IMAGE_NAME

      - name: Build and push ShkedNginx image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-nginx:latest
          docker build -t $IMAGE_NAME ./nginx
          docker push $IMAGE_NAME
